name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install dependencies
        run: npm install

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli@latest

      - name: Run tests
        run: npm test

      - name: Build frontend
        run: npm run frontend:build

      - name: Build Tauri app (Universal Binary)
        run: tauri build --target universal-apple-darwin

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          body: |
            ## Download

            **macOS Universal Binary** (Intel + Apple Silicon):
            - Download the `.dmg` file below for easy installation
            - Or download the `.app.tar.gz` for manual installation

            ## Installation

            ### Using DMG (Recommended)
            1. Download `moss_*_macOS.dmg`
            2. Open the downloaded file
            3. Drag moss.app to your Applications folder

            ### Using App Bundle
            1. Download `moss_*_macOS.app.tar.gz`
            2. Extract the archive
            3. Move moss.app to your Applications folder

            ---
            **Built with:** Universal macOS binary (Intel + Apple Silicon)
            **Commit:** ${{ github.sha }}
          files: |
            src-tauri/target/universal-apple-darwin/release/bundle/dmg/*.dmg
            src-tauri/target/universal-apple-darwin/release/bundle/macos/*.app.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true